(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.hkData = factory();
  }
})(typeof self !== 'undefined' ? self : this, function () {
  const defaultPrograms = {
    figma: {
      name: 'Figma',
      color: '#1abcfe',
      sc: [
        { id: 1, a: 'Быстрые действия', k: ['Ctrl', '/'], d: 'easy' },
        { id: 2, a: 'Быстрый поиск', k: ['Ctrl', 'P'], d: 'easy' },
        { id: 3, a: 'Очистить выделение / выход', k: ['Esc'], d: 'easy' },
        { id: 4, a: 'Перемещение', k: ['V'], d: 'easy' },
        { id: 5, a: 'Рамка', k: ['F'], d: 'easy' },
        { id: 6, a: 'Прямоугольник', k: ['R'], d: 'easy' },
        { id: 7, a: 'Эллипс', k: ['O'], d: 'easy' },
        { id: 8, a: 'Линия', k: ['L'], d: 'easy' },
        { id: 9, a: 'Перо', k: ['P'], d: 'easy' },
        { id: 10, a: 'Карандаш', k: ['Shift', 'P'], d: 'medium' },
        { id: 11, a: 'Текст', k: ['T'], d: 'easy' },
        { id: 12, a: 'Рука', k: ['H'], d: 'easy' },
        { id: 13, a: 'Масштаб', k: ['Z'], d: 'easy' },
        { id: 14, a: 'Выделить все', k: ['Ctrl', 'A'], d: 'easy' },
        { id: 15, a: 'Снять выделение', k: ['Ctrl', 'Shift', 'A'], d: 'medium' },
        { id: 16, a: 'Группировать', k: ['Ctrl', 'G'], d: 'easy' },
        { id: 17, a: 'Разгруппировать', k: ['Ctrl', 'Shift', 'G'], d: 'medium' },
        { id: 18, a: 'Вперёд', k: ['Ctrl', ']'], d: 'medium' },
        { id: 19, a: 'На передний план', k: ['Ctrl', 'Shift', ']'], d: 'medium' },
        { id: 20, a: 'Назад', k: ['Ctrl', '['], d: 'medium' },
        { id: 21, a: 'На задний план', k: ['Ctrl', 'Shift', '['], d: 'medium' },
        { id: 22, a: 'Дублировать', k: ['Ctrl', 'D'], d: 'easy' },
        { id: 23, a: 'Выровнять влево', k: ['Alt', 'A'], d: 'medium' },
        { id: 24, a: 'Выровнять вправо', k: ['Alt', 'D'], d: 'medium' },
        { id: 25, a: 'Выровнять вверх', k: ['Alt', 'W'], d: 'medium' },
        { id: 26, a: 'Выровнять вниз', k: ['Alt', 'S'], d: 'medium' },
        { id: 27, a: 'Выровнять по центру Х', k: ['Alt', 'H'], d: 'medium' },
        { id: 28, a: 'Выровнять по центру Y', k: ['Alt', 'V'], d: 'medium' },
        { id: 29, a: 'Авто-лейаут', k: ['Shift', 'A'], d: 'medium' },
        { id: 30, a: 'Boolean: Объединить', k: ['Ctrl', 'Alt', 'B'], d: 'hard' },
        { id: 31, a: 'Boolean: Вычесть', k: ['Ctrl', 'Alt', 'S'], d: 'hard' },
        { id: 32, a: 'Boolean: Пересечь', k: ['Ctrl', 'Alt', 'I'], d: 'hard' },
        { id: 33, a: 'Boolean: Исключить', k: ['Ctrl', 'Alt', 'X'], d: 'hard' },
        { id: 34, a: 'Создать компонент', k: ['Ctrl', 'Alt', 'K'], d: 'medium' },
        { id: 35, a: 'Отсоединить экземпляр', k: ['Ctrl', 'Shift', 'B'], d: 'medium' },
        { id: 36, a: 'Увеличить', k: ['Ctrl', '+'], d: 'easy' },
        { id: 37, a: 'Уменьшить', k: ['Ctrl', '-'], d: 'easy' },
        { id: 38, a: 'Масштаб 100%', k: ['Ctrl', '0'], d: 'easy' },
        { id: 39, a: 'Вписать в экран', k: ['Ctrl', '1'], d: 'easy' },
        { id: 40, a: 'Вписать выделение', k: ['Ctrl', '2'], d: 'medium' },
        { id: 41, a: 'Линейки вкл/выкл', k: ['Ctrl', "'"], d: 'medium' },
        { id: 42, a: 'Экспорт', k: ['Ctrl', 'Shift', 'E'], d: 'medium' },
      ],
    },
    vscode: {
      name: 'VS Code',
      color: '#007acc',
      sc: [
        { id: 1, a: 'Палитра команд', k: ['Ctrl', 'Shift', 'P'], d: 'easy' },
        { id: 2, a: 'Быстрое открытие', k: ['Ctrl', 'P'], d: 'easy' },
        { id: 3, a: 'Новое окно', k: ['Ctrl', 'Shift', 'N'], d: 'easy' },
        { id: 4, a: 'Закрыть окно', k: ['Ctrl', 'Shift', 'W'], d: 'easy' },
        { id: 5, a: 'Настройки', k: ['Ctrl', ','], d: 'easy' },
        { id: 6, a: 'Новый файл', k: ['Ctrl', 'N'], d: 'easy' },
        { id: 7, a: 'Открыть файл', k: ['Ctrl', 'O'], d: 'easy' },
        { id: 8, a: 'Сохранить', k: ['Ctrl', 'S'], d: 'easy' },
        { id: 9, a: 'Сохранить как', k: ['Ctrl', 'Shift', 'S'], d: 'easy' },
        { id: 10, a: 'Закрыть редактор', k: ['Ctrl', 'W'], d: 'easy' },
        { id: 11, a: 'Закрыть все', k: ['Ctrl', 'K', 'W'], d: 'medium' },
        { id: 12, a: 'Восстановить закрытый', k: ['Ctrl', 'Shift', 'T'], d: 'medium' },
        { id: 13, a: 'Вырезать', k: ['Ctrl', 'X'], d: 'easy' },
        { id: 14, a: 'Копировать', k: ['Ctrl', 'C'], d: 'easy' },
        { id: 15, a: 'Строку вверх', k: ['Alt', '↑'], d: 'medium' },
        { id: 16, a: 'Строку вниз', k: ['Alt', '↓'], d: 'medium' },
        { id: 17, a: 'Копировать строку вниз', k: ['Shift', 'Alt', '↓'], d: 'medium' },
        { id: 18, a: 'Копировать строку вверх', k: ['Shift', 'Alt', '↑'], d: 'medium' },
        { id: 19, a: 'Вставить строку ниже', k: ['Ctrl', 'Enter'], d: 'medium' },
        { id: 20, a: 'Вставить строку выше', k: ['Ctrl', 'Shift', 'Enter'], d: 'medium' },
        { id: 21, a: 'Удалить строку', k: ['Ctrl', 'Shift', 'K'], d: 'easy' },
        { id: 22, a: 'Отступ вправо', k: ['Ctrl', ']'], d: 'easy' },
        { id: 23, a: 'Отступ влево', k: ['Ctrl', '['], d: 'easy' },
        { id: 24, a: 'Отменить', k: ['Ctrl', 'Z'], d: 'easy' },
        { id: 25, a: 'Повторить', k: ['Ctrl', 'Y'], d: 'easy' },
        { id: 26, a: 'Добавить курсор', k: ['Ctrl', 'Alt', '↓'], d: 'hard' },
        { id: 27, a: 'Добавить следующее совпадение', k: ['Ctrl', 'D'], d: 'medium' },
        { id: 28, a: 'Выделить все вхождения', k: ['Ctrl', 'Shift', 'L'], d: 'hard' },
        { id: 29, a: 'Выделить строку', k: ['Ctrl', 'L'], d: 'easy' },
        { id: 30, a: 'Поиск', k: ['Ctrl', 'F'], d: 'easy' },
        { id: 31, a: 'Замена', k: ['Ctrl', 'H'], d: 'easy' },
        { id: 32, a: 'Следующее совпадение', k: ['F3'], d: 'easy' },
        { id: 33, a: 'Поиск в файлах', k: ['Ctrl', 'Shift', 'F'], d: 'easy' },
        { id: 34, a: 'Замена в файлах', k: ['Ctrl', 'Shift', 'H'], d: 'medium' },
        { id: 35, a: 'К определению', k: ['F12'], d: 'medium' },
        { id: 36, a: 'Просмотр определения', k: ['Alt', 'F12'], d: 'medium' },
        { id: 37, a: 'К ссылкам', k: ['Shift', 'F12'], d: 'hard' },
        { id: 38, a: 'Переименовать символ', k: ['F2'], d: 'medium' },
        { id: 39, a: 'К символу в файле', k: ['Ctrl', 'Shift', 'O'], d: 'hard' },
        { id: 40, a: 'К символу в проекте', k: ['Ctrl', 'T'], d: 'hard' },
        { id: 41, a: 'Форматировать документ', k: ['Shift', 'Alt', 'F'], d: 'medium' },
        { id: 42, a: 'Форматировать выделение', k: ['Ctrl', 'K', 'Ctrl', 'F'], d: 'hard' },
        { id: 43, a: 'Комментарий строки', k: ['Ctrl', '/'], d: 'easy' },
        { id: 44, a: 'Блочный комментарий', k: ['Shift', 'Alt', 'A'], d: 'medium' },
        { id: 45, a: 'Быстрые исправления', k: ['Ctrl', '.'], d: 'medium' },
        { id: 46, a: 'Разделить редактор', k: ['Ctrl', '\\'], d: 'medium' },
        { id: 47, a: 'Фокус группа 1', k: ['Ctrl', '1'], d: 'easy' },
        { id: 48, a: 'Боковая панель', k: ['Ctrl', 'B'], d: 'easy' },
        { id: 49, a: 'Панель', k: ['Ctrl', 'J'], d: 'easy' },
        { id: 50, a: 'Проводник', k: ['Ctrl', 'Shift', 'E'], d: 'easy' },
        { id: 52, a: 'Система контроля версий', k: ['Ctrl', 'Shift', 'G'], d: 'easy' },
        { id: 53, a: 'Отладка', k: ['Ctrl', 'Shift', 'D'], d: 'medium' },
        { id: 54, a: 'Расширения', k: ['Ctrl', 'Shift', 'X'], d: 'easy' },
        { id: 55, a: 'Терминал', k: ['Ctrl', '`'], d: 'easy' },
        { id: 56, a: 'Старт/продолжить отладку', k: ['F5'], d: 'medium' },
        { id: 57, a: 'Остановить отладку', k: ['Shift', 'F5'], d: 'medium' },
        { id: 58, a: 'Точка останова', k: ['F9'], d: 'medium' },
        { id: 59, a: 'Шаг через', k: ['F10'], d: 'medium' },
        { id: 60, a: 'Шаг в', k: ['F11'], d: 'medium' },
      ],
    },
    chrome: {
      name: 'Google Chrome',
      color: '#4285f4',
      sc: [
        { id: 1, a: 'Новая вкладка', k: ['Ctrl', 'T'], d: 'easy' },
        { id: 2, a: 'Закрыть вкладку', k: ['Ctrl', 'W'], d: 'easy' },
        { id: 3, a: 'Восстановить вкладку', k: ['Ctrl', 'Shift', 'T'], d: 'medium' },
        { id: 4, a: 'Новое окно', k: ['Ctrl', 'N'], d: 'easy' },
        { id: 5, a: 'Окно инкогнито', k: ['Ctrl', 'Shift', 'N'], d: 'medium' },
        { id: 6, a: 'Адресная строка', k: ['Ctrl', 'L'], d: 'easy' },
        { id: 7, a: 'Обновить страницу', k: ['Ctrl', 'R'], d: 'easy' },
        { id: 8, a: 'Обновить без кеша', k: ['Ctrl', 'Shift', 'R'], d: 'medium' },
        { id: 9, a: 'Поиск по странице', k: ['Ctrl', 'F'], d: 'easy' },
        { id: 10, a: 'Следующее совпадение', k: ['F3'], d: 'easy' },
        { id: 11, a: 'Предыдущее совпадение', k: ['Shift', 'F3'], d: 'medium' },
        { id: 12, a: 'Добавить в закладки', k: ['Ctrl', 'D'], d: 'easy' },
        { id: 13, a: 'Менеджер закладок', k: ['Ctrl', 'Shift', 'O'], d: 'medium' },
        { id: 14, a: 'История', k: ['Ctrl', 'H'], d: 'easy' },
        { id: 15, a: 'Загрузки', k: ['Ctrl', 'J'], d: 'easy' },
        { id: 16, a: 'DevTools', k: ['Ctrl', 'Shift', 'I'], d: 'medium' },
        { id: 17, a: 'Просмотр кода страницы', k: ['Ctrl', 'U'], d: 'easy' },
        { id: 18, a: 'Печать', k: ['Ctrl', 'P'], d: 'easy' },
        { id: 19, a: 'Полноэкранный режим', k: ['F11'], d: 'easy' },
        { id: 20, a: 'Следующая вкладка', k: ['Ctrl', 'Tab'], d: 'medium' },
        { id: 21, a: 'Предыдущая вкладка', k: ['Ctrl', 'Shift', 'Tab'], d: 'medium' },
        { id: 22, a: 'Перейти к вкладке 1', k: ['Ctrl', '1'], d: 'easy' },
        { id: 23, a: 'Перейти к последней вкладке', k: ['Ctrl', '9'], d: 'easy' },
      ],
    },
    terminal: {
      name: 'Windows Terminal',
      color: '#4d4d4d',
      sc: [
        { id: 1, a: 'Новая вкладка', k: ['Ctrl', 'Shift', 'T'], d: 'easy' },
        { id: 2, a: 'Закрыть вкладку', k: ['Ctrl', 'Shift', 'W'], d: 'easy' },
        { id: 3, a: 'Новое окно', k: ['Ctrl', 'Shift', 'N'], d: 'easy' },
        { id: 4, a: 'Полный экран', k: ['Alt', 'Enter'], d: 'easy' },
        { id: 5, a: 'Поиск', k: ['Ctrl', 'Shift', 'F'], d: 'easy' },
        { id: 6, a: 'Копировать', k: ['Ctrl', 'Shift', 'C'], d: 'easy' },
        { id: 7, a: 'Вставить', k: ['Ctrl', 'Shift', 'V'], d: 'easy' },
        { id: 8, a: 'Разделить панель', k: ['Alt', 'Shift', 'D'], d: 'medium' },
        { id: 9, a: 'Разделить вниз', k: ['Alt', 'Shift', '+'], d: 'medium' },
        { id: 10, a: 'Разделить вправо', k: ['Alt', 'Shift', '-'], d: 'medium' },
        { id: 11, a: 'Переключить панель влево', k: ['Alt', '←'], d: 'medium' },
        { id: 12, a: 'Переключить панель вправо', k: ['Alt', '→'], d: 'medium' },
        { id: 13, a: 'Переключить панель вверх', k: ['Alt', '↑'], d: 'medium' },
        { id: 14, a: 'Переключить панель вниз', k: ['Alt', '↓'], d: 'medium' },
      ],
    },
    powershell: {
      name: 'PowerShell',
      color: '#012456',
      sc: [
        { id: 1, a: 'Новая строка', k: ['Shift', 'Enter'], d: 'easy' },
        { id: 2, a: 'Влево', k: ['←'], d: 'easy' },
        { id: 3, a: 'Вправо', k: ['→'], d: 'easy' },
        { id: 4, a: 'По слову влево', k: ['Ctrl', '←'], d: 'easy' },
        { id: 5, a: 'По слову вправо', k: ['Ctrl', '→'], d: 'easy' },
        { id: 6, a: 'Начало строки', k: ['Home'], d: 'easy' },
        { id: 7, a: 'Конец строки', k: ['End'], d: 'easy' },
        { id: 8, a: 'Backspace', k: ['Backspace'], d: 'easy' },
        { id: 9, a: 'Delete', k: ['Delete'], d: 'easy' },
        { id: 10, a: 'Автодополнение', k: ['Tab'], d: 'easy' },
        { id: 11, a: 'Меню завершений', k: ['Ctrl', 'Space'], d: 'medium' },
        { id: 12, a: 'Очистить экран', k: ['Ctrl', 'L'], d: 'easy' },
        { id: 13, a: 'Предыдущая команда', k: ['↑'], d: 'easy' },
        { id: 14, a: 'Следующая команда', k: ['↓'], d: 'easy' },
      ],
    },
    photoshop: {
      name: 'Adobe Photoshop',
      color: '#31a8ff',
      sc: [
        { id: 1, a: 'Новый', k: ['Ctrl', 'N'], d: 'easy' },
        { id: 2, a: 'Открыть', k: ['Ctrl', 'O'], d: 'easy' },
        { id: 3, a: 'Сохранить', k: ['Ctrl', 'S'], d: 'easy' },
        { id: 4, a: 'Сохранить как', k: ['Ctrl', 'Shift', 'S'], d: 'easy' },
        { id: 5, a: 'Закрыть', k: ['Ctrl', 'W'], d: 'easy' },
        { id: 6, a: 'Отменить/Повторить', k: ['Ctrl', 'Z'], d: 'easy' },
        { id: 7, a: 'Шаг назад', k: ['Ctrl', 'Alt', 'Z'], d: 'medium' },
        { id: 8, a: 'Шаг вперёд', k: ['Ctrl', 'Shift', 'Z'], d: 'medium' },
        { id: 9, a: 'Увеличить', k: ['Ctrl', '+'], d: 'easy' },
        { id: 10, a: 'Уменьшить', k: ['Ctrl', '-'], d: 'easy' },
        { id: 11, a: 'Вписать в экран', k: ['Ctrl', '0'], d: 'easy' },
        { id: 12, a: '100%', k: ['Ctrl', '1'], d: 'easy' },
        { id: 13, a: 'Рука', k: ['H'], d: 'easy' },
        { id: 14, a: 'Масштаб', k: ['Z'], d: 'easy' },
        { id: 15, a: 'Линейки вкл/выкл', k: ['Ctrl', 'R'], d: 'medium' },
        { id: 16, a: 'Направляющие вкл/выкл', k: ['Ctrl', ';'], d: 'medium' },
        { id: 17, a: 'Сетка вкл/выкл', k: ['Ctrl', 'Shift', ';'], d: 'medium' },
        { id: 18, a: 'Скрыть панели', k: ['Tab'], d: 'easy' },
        { id: 19, a: 'Перемещение', k: ['V'], d: 'easy' },
        { id: 20, a: 'Выделение', k: ['M'], d: 'easy' },
        { id: 21, a: 'Лассо', k: ['L'], d: 'easy' },
        { id: 22, a: 'Волшебная палочка', k: ['W'], d: 'easy' },
        { id: 23, a: 'Обрезка', k: ['C'], d: 'easy' },
        { id: 24, a: 'Пипетка', k: ['I'], d: 'easy' },
        { id: 25, a: 'Кисть', k: ['B'], d: 'easy' },
        { id: 26, a: 'Штамп', k: ['S'], d: 'easy' },
        { id: 27, a: 'Ластик', k: ['E'], d: 'easy' },
        { id: 28, a: 'Градиент', k: ['G'], d: 'easy' },
        { id: 29, a: 'Текст', k: ['T'], d: 'easy' },
        { id: 30, a: 'Перо', k: ['P'], d: 'medium' },
        { id: 31, a: 'Фигуры', k: ['U'], d: 'easy' },
        { id: 32, a: 'Цвета по умолчанию', k: ['D'], d: 'easy' },
        { id: 33, a: 'Обменять цвета', k: ['X'], d: 'easy' },
        { id: 34, a: 'Быстрая маска', k: ['Q'], d: 'medium' },
        { id: 35, a: 'Уменьшить кисть', k: ['['], d: 'medium' },
        { id: 36, a: 'Увеличить кисть', k: [']'], d: 'medium' },
        { id: 37, a: 'Выделить всё', k: ['Ctrl', 'A'], d: 'easy' },
        { id: 38, a: 'Снять выделение', k: ['Ctrl', 'D'], d: 'easy' },
        { id: 39, a: 'Инвертировать выделение', k: ['Ctrl', 'Shift', 'I'], d: 'medium' },
        { id: 40, a: 'Новый слой (копия)', k: ['Ctrl', 'J'], d: 'medium' },
        { id: 41, a: 'Объединить вниз', k: ['Ctrl', 'E'], d: 'medium' },
        { id: 42, a: 'Объединить видимые', k: ['Ctrl', 'Shift', 'E'], d: 'medium' },
        { id: 43, a: 'Группировать слои', k: ['Ctrl', 'G'], d: 'medium' },
        { id: 44, a: 'Разгруппировать', k: ['Ctrl', 'Shift', 'G'], d: 'medium' },
        { id: 45, a: 'Слой выше', k: ['Ctrl', ']'], d: 'medium' },
        { id: 46, a: 'Слой ниже', k: ['Ctrl', '['], d: 'medium' },
        { id: 47, a: 'Создать маску', k: ['Ctrl', 'Alt', 'G'], d: 'hard' },
        { id: 48, a: 'Новый слой', k: ['Ctrl', 'Shift', 'N'], d: 'easy' },
        { id: 49, a: 'Свободное трансформирование', k: ['Ctrl', 'T'], d: 'medium' },
        { id: 50, a: 'Инвертировать', k: ['Ctrl', 'I'], d: 'medium' },
      ],
    },
    comfyui: {
      name: 'ComfyUI',
      color: '#7c3aed',
      sc: [
        { id: 1, a: 'Запустить генерацию', k: ['Ctrl', 'Enter'], d: 'easy' },
        { id: 2, a: 'Запустить первым', k: ['Ctrl', 'Shift', 'Enter'], d: 'medium' },
        { id: 3, a: 'Отменить генерацию', k: ['Ctrl', 'Alt', 'Enter'], d: 'medium' },
        { id: 4, a: 'Отменить', k: ['Ctrl', 'Z'], d: 'easy' },
        { id: 5, a: 'Повторить', k: ['Ctrl', 'Y'], d: 'easy' },
        { id: 6, a: 'Сохранить workflow', k: ['Ctrl', 'S'], d: 'easy' },
        { id: 7, a: 'Загрузить workflow', k: ['Ctrl', 'O'], d: 'easy' },
        { id: 8, a: 'Выделить все', k: ['Ctrl', 'A'], d: 'easy' },
        { id: 9, a: 'Свернуть узлы', k: ['Alt', 'C'], d: 'medium' },
        { id: 10, a: 'Заглушить узлы', k: ['Ctrl', 'M'], d: 'medium' },
        { id: 11, a: 'Обойти узлы', k: ['Ctrl', 'B'], d: 'medium' },
        { id: 12, a: 'Удалить', k: ['Delete'], d: 'easy' },
        { id: 13, a: 'Удалить граф', k: ['Ctrl', 'Backspace'], d: 'medium' },
        { id: 14, a: 'Копировать', k: ['Ctrl', 'C'], d: 'easy' },
        { id: 15, a: 'Вставить', k: ['Ctrl', 'V'], d: 'easy' },
        { id: 16, a: 'Загрузить по умолчанию', k: ['Ctrl', 'D'], d: 'easy' },
        { id: 17, a: 'Увеличить', k: ['Alt', '+'], d: 'easy' },
        { id: 18, a: 'Уменьшить', k: ['Alt', '-'], d: 'easy' },
        { id: 19, a: 'Закрепить узлы', k: ['P'], d: 'medium' },
        { id: 20, a: 'Группировать узлы', k: ['Ctrl', 'G'], d: 'medium' },
        { id: 21, a: 'Панель очереди', k: ['Q'], d: 'easy' },
        { id: 22, a: 'Панель истории', k: ['H'], d: 'easy' },
        { id: 23, a: 'Обновить граф', k: ['R'], d: 'easy' },
        { id: 24, a: 'Меню вкл/выкл', k: ['F'], d: 'easy' },
        { id: 25, a: 'Вписать в экран', k: ['.'], d: 'easy' },
      ],
    },
    notion: {
      name: 'Notion',
      color: '#000000',
      sc: [
        { id: 1, a: 'Поиск / переход', k: ['Ctrl', 'P'], d: 'easy' },
        { id: 2, a: 'Вставить ссылку', k: ['Ctrl', 'K'], d: 'easy' },
        { id: 3, a: 'Все горячие клавиши', k: ['Ctrl', '/'], d: 'easy' },
        { id: 4, a: 'Назад', k: ['Ctrl', '['], d: 'easy' },
        { id: 5, a: 'Вперёд', k: ['Ctrl', ']'], d: 'easy' },
        { id: 6, a: 'Тёмная тема', k: ['Ctrl', 'Shift', 'L'], d: 'easy' },
        { id: 7, a: 'Новый блок', k: ['Enter'], d: 'easy' },
        { id: 8, a: 'Мягкий перенос', k: ['Shift', 'Enter'], d: 'easy' },
        { id: 9, a: 'Комментарий', k: ['Ctrl', 'Shift', 'M'], d: 'medium' },
        { id: 10, a: 'Дублировать блок', k: ['Ctrl', 'D'], d: 'easy' },
        { id: 11, a: 'Переместить блок вверх', k: ['Ctrl', 'Shift', '↑'], d: 'medium' },
        { id: 12, a: 'Переместить блок вниз', k: ['Ctrl', 'Shift', '↓'], d: 'medium' },
        { id: 13, a: 'Заголовок 1', k: ['Ctrl', 'Alt', '1'], d: 'easy' },
        { id: 14, a: 'Заголовок 2', k: ['Ctrl', 'Alt', '2'], d: 'easy' },
        { id: 15, a: 'Заголовок 3', k: ['Ctrl', 'Alt', '3'], d: 'easy' },
        { id: 16, a: 'Обычный текст', k: ['Ctrl', 'Shift', '0'], d: 'easy' },
        { id: 17, a: 'Маркированный список', k: ['Ctrl', 'Shift', '7'], d: 'easy' },
        { id: 18, a: 'Нумерованный список', k: ['Ctrl', 'Shift', '8'], d: 'easy' },
        { id: 19, a: 'Чеклист', k: ['Ctrl', 'Shift', '9'], d: 'easy' },
        { id: 20, a: 'Жирный', k: ['Ctrl', 'B'], d: 'easy' },
        { id: 21, a: 'Курсив', k: ['Ctrl', 'I'], d: 'easy' },
        { id: 22, a: 'Подчёркнутый', k: ['Ctrl', 'U'], d: 'easy' },
        { id: 23, a: 'Зачёркнутый', k: ['Ctrl', 'Shift', 'S'], d: 'medium' },
        { id: 24, a: 'Код (inline)', k: ['Ctrl', 'E'], d: 'medium' },
        { id: 25, a: 'Выделить', k: ['Ctrl', 'Shift', 'H'], d: 'medium' },
      ],
    },
    obsidian: {
      name: 'Obsidian',
      color: '#a855f7',
      sc: [
        { id: 1, a: 'Палитра команд', k: ['Ctrl', 'P'], d: 'easy' },
        { id: 2, a: 'Быстрое открытие', k: ['Ctrl', 'O'], d: 'easy' },
        { id: 3, a: 'Новая заметка', k: ['Ctrl', 'N'], d: 'easy' },
        { id: 4, a: 'Сохранить файл', k: ['Ctrl', 'S'], d: 'easy' },
        { id: 5, a: 'Редактирование/Чтение', k: ['Ctrl', 'E'], d: 'easy' },
        { id: 6, a: 'Настройки', k: ['Ctrl', ','], d: 'easy' },
        { id: 7, a: 'Поиск в файле', k: ['Ctrl', 'F'], d: 'easy' },
        { id: 8, a: 'Замена в файле', k: ['Ctrl', 'H'], d: 'easy' },
        { id: 9, a: 'Поиск в хранилище', k: ['Ctrl', 'Shift', 'F'], d: 'easy' },
        { id: 10, a: 'Назад', k: ['Alt', '←'], d: 'easy' },
        { id: 11, a: 'Вперёд', k: ['Alt', '→'], d: 'easy' },
        { id: 12, a: 'Закрыть вкладку', k: ['Ctrl', 'W'], d: 'easy' },
        { id: 13, a: 'Следующая вкладка', k: ['Ctrl', 'Tab'], d: 'easy' },
        { id: 14, a: 'Предыдущая вкладка', k: ['Ctrl', 'Shift', 'Tab'], d: 'medium' },
        { id: 15, a: 'Жирный', k: ['Ctrl', 'B'], d: 'easy' },
        { id: 16, a: 'Курсив', k: ['Ctrl', 'I'], d: 'easy' },
        { id: 17, a: 'Вставить ссылку', k: ['Ctrl', 'K'], d: 'easy' },
      ],
    },
    razer_naga: {
      name: 'Razer Naga V2 Hyperspeed',
      color: '#10b981',
      sc: [
        { id: 1, a: 'Copy', k: ['Ctrl', 'C'], d: 'easy' },
        { id: 2, a: 'Paste', k: ['Ctrl', 'V'], d: 'easy' },
        { id: 3, a: 'Cut', k: ['Ctrl', 'X'], d: 'easy' },
        { id: 4, a: 'Undo', k: ['Ctrl', 'Z'], d: 'easy' },
        { id: 5, a: 'Redo', k: ['Ctrl', 'Shift', 'Z'], d: 'medium' },
        { id: 6, a: 'Delete', k: ['Del'], d: 'easy' },
        { id: 7, a: 'Num Enter', k: ['Enter'], d: 'easy' },
        { id: 8, a: 'Esc', k: ['Esc'], d: 'easy' },
        { id: 9, a: 'Backspace', k: ['Backspace'], d: 'easy' },
        { id: 10, a: 'Назад (Alt+Left)', k: ['Alt', '←'], d: 'easy' },
        { id: 11, a: 'Вперёд (Alt+Right)', k: ['Alt', '→'], d: 'easy' },
        { id: 12, a: 'Up', k: ['↑'], d: 'easy' },
        { id: 13, a: 'Down', k: ['↓'], d: 'easy' },
        { id: 14, a: 'Left', k: ['←'], d: 'easy' },
        { id: 15, a: 'Right', k: ['→'], d: 'easy' },
      ],
    },
    pie_menu: {
      name: 'Pie Menu',
      color: '#f59e0b',
      sc: [
        { id: 1, a: 'Quick-Pie', k: ['F18', 'Q'], d: 'easy' },
        { id: 2, a: 'Folders-Pie', k: ['F18', 'E'], d: 'easy' },
        { id: 3, a: 'Settings-Pie', k: ['F18', 'S'], d: 'easy' },
        { id: 4, a: 'Actions-Pie', k: ['F18', 'A'], d: 'easy' },
        { id: 5, a: 'Window-Pie', k: ['F18', 'W'], d: 'easy' },
        { id: 6, a: 'Apps', k: ['F18', '4'], d: 'easy' },
        { id: 7, a: 'Figma Pie', k: ['F18', '2'], d: 'easy' },
        { id: 8, a: 'Punto-Pie', k: ['F18', '1'], d: 'easy' },
        { id: 9, a: 'Search-Pie', k: ['F18', 'F'], d: 'easy' },
        { id: 10, a: 'Edit-Pie', k: ['F18', 'C'], d: 'easy' },
        { id: 11, a: 'Terminals-Pie', k: ['F18', '3'], d: 'easy' },
      ],
    },
    logi_g815_m1: {
      name: 'Logi G815 (M1)',
      color: '#4d4d4d',
      sc: [
        { id: 1, a: 'F18', k: ['F18'], d: 'easy' },
        { id: 2, a: 'Win+Shift+E', k: ['Win', 'Shift', 'E'], d: 'medium' },
        { id: 3, a: 'End', k: ['End'], d: 'easy' },
        { id: 4, a: 'Home', k: ['Home'], d: 'easy' },
        { id: 5, a: 'Смена раскладки', k: ['Alt', 'Shift'], d: 'easy' },
      ],
    },
    logi_g815_m2: {
      name: 'Logi G815 (M2)',
      color: '#007acc',
      sc: [
        { id: 1, a: 'F2', k: ['F2'], d: 'easy' },
        { id: 2, a: 'F3', k: ['F3'], d: 'easy' },
        { id: 3, a: 'F4', k: ['F4'], d: 'easy' },
        { id: 4, a: 'F5', k: ['F5'], d: 'easy' },
      ],
    },
    logi_g815_m3: {
      name: 'Logi G815 (M3)',
      color: '#a855f7',
      sc: [
        { id: 1, a: 'F19', k: ['F19'], d: 'easy' },
        { id: 2, a: 'F18', k: ['F18'], d: 'easy' },
        { id: 3, a: 'F17', k: ['F17'], d: 'easy' },
        { id: 4, a: 'F16', k: ['F16'], d: 'easy' },
        { id: 5, a: 'F15', k: ['F15'], d: 'easy' },
      ],
    },
    powertoys: {
      name: 'Windows PowerToys',
      color: '#31a8ff',
      sc: [
        { id: 1, a: 'PowerToys Run', k: ['Alt', 'Space'], d: 'easy' },
        { id: 2, a: 'Color Picker', k: ['Win', 'Shift', 'C'], d: 'easy' },
        { id: 3, a: 'FancyZones Editor', k: ['Win', 'Shift', '`'], d: 'medium' },
        { id: 4, a: 'Text Extractor', k: ['Win', 'Shift', 'T'], d: 'medium' },
        { id: 5, a: 'Screen Ruler', k: ['Win', 'Shift', 'M'], d: 'medium' },
      ],
    },
  };

  const colorOptions = [
    '#1abcfe',
    '#007acc',
    '#4285f4',
    '#4d4d4d',
    '#012456',
    '#31a8ff',
    '#7c3aed',
    '#000000',
    '#a855f7',
    '#ef4444',
    '#10b981',
    '#f59e0b',
    '#ec4899',
  ];

  return {
    defaultPrograms,
    colorOptions,
  };
});
